### ISSUE TITLE
转载链接申请

### ISSUE THREAD

**Issue by wxystudio** [THU-feiyue/THU-feiyue#40]
您好：
    我是西安交通大学校友王啸宇，近日热心校友新建了一个bbs，xjtu.men，目前我们在大力发展飞跃重洋 版块。我想申请将贵校的飞跃网站链接挂在我们的bbs上做参考，考虑到版权问题，不知道是否允许？如果出于隐私问题不允许，我也非常理解并感谢

**Comment by SamSeven777** [comment]
您好，非常感谢您对我们工作的认可和支持！已添加CC BY-NC 4.0许可证授权相关内容，请遵循许可证要求进行参考引用。
https://creativecommons.org/licenses/by-nc/4.0/deed.zh
祝好
